---
networks:
    proxy:
        external: true

services:
    composerize:
        stdin_open: true
        tty: true
        image: maaxgr/composerize:latest
        command: composerize \
    echo-server:
        container_name: web1
        networks:
            - proxy
        image: jmalloc/echo-server:latest
