---
- name: Update Proxmox Hosts
  hosts: Proxmox
  gather_facts: true
  become: true
  vars:
    gotify_ip: "{{ gotify_ip }}"  # Your Gotify host IP goes here
    gotify_token: "{{ gotify_token }}"  # Your app token goes here

  tasks:
    - name: Get Hostnames
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }}:{{ ansible_default_ipv4.address }}"

    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: true

    - name: Notify via Gotify
      ansible.builtin.uri:
        url: 'https://{{ gotify_ip }}/message?token={{ gotify_token }}'
        method: POST
        body:
          title:
            content: Proxmox Update
          message:
            content: The Proxmox Update playbook has completed for {{ ansible_host }} and a required reboot is {{ reboot_required_file.stat.exists == true }}.
          priority:
            content: '5'
        body_format: form-multipart
      register: result
