version: "3.9"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    networks:
      - proxy
    volumes:
      - grafana-volume:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local.example.com`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    networks:
      - proxy
    volumes:
      - influxdb-volume:/var/lib/influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.local.example.com`)"
      - "traefik.http.routers.influxdb.entrypoints=https"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8080"


networks:
  proxy:
    external: true

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true