---
services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: always
    container_name: "redlib"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redlib.tls=true"
      - "traefik.http.routers.redlib.rule=Host(`redlib.int.home.lab`)"
      - "traefik.http.services.redlib.loadbalancer.server.port=8080"
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    env_file: .env
    networks:
      - redlib
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s

networks:
  proxy:
    external: true