version: "3.8"
services:
  playit:
    container_name: playit
    image: ghcr.io/playit-cloud/playit-agent:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/docker/playit:/app/config
    environment:
      - SECRET_KEY=${PLAYIT_SECRET_KEY}
networks: {}
