name: Update copyright year in license file

on:
  schedule:
    - cron: '0 3 1 1 *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Update license year
        uses: p3lim/license-year-updater@v2
        with:
          files: |
            LICENSE